"""Formats skill output as a polished markdown report."""
import sys
from pathlib import Path
from datetime import datetime

def render_report(result: dict, skill_name: str = "") -> str:
    if result.get("status") == "error":
        return f"# Error\n\n{result.get('error', 'Unknown error occurred.')}"

    output = result.get("output", "")
    exec_time = result.get("execution_time_seconds", 0)
    source = result.get("source", "live")
    now = datetime.now().strftime("%d %b %Y, %H:%M")

    footer = f"\n\n---\n*Generated by IM Agentic OS"
    if skill_name:
        footer += f" | {skill_name}"
    footer += f" | {now}"
    if exec_time:
        footer += f" | {exec_time:.1f}s"
    if source == "mock":
        footer += " | Demo Mode"
    footer += "*"

    return output + footer

if __name__ == "__main__":
    sample = {
        "status": "success",
        "output": "# Sample Output\n\nThis is a sample report.",
        "execution_time_seconds": 12.3,
        "source": "mock"
    }
    print(render_report(sample, "SRS Creator"))
