"""
HTTP client between the Streamlit UI and the FastAPI backend.

Backend lives at http://localhost:8000. If it is unreachable (connection refused)
we fall back to a mock response so the UI stays usable during demos. Any other
error (HTTP 4xx/5xx, timeout) is surfaced verbatim.
"""
import json
import os
import random
import time

import requests

SANDBOX_URL = os.environ.get("SANDBOX_URL", "http://localhost:8000")
RUN_TIMEOUT_SECONDS = 180


# ── Mock fallback content (used only when backend is unreachable) ─────────────
MOCK_SRS = """# Software Requirements Specification — (mock)
*Backend offline — this is a placeholder generated by the frontend.*

Start the backend with `uvicorn backend.api:app --port 8000` to get a real run.
"""

MOCK_TEST_CASES = """# Test Cases — (mock)
*Backend offline — this is a placeholder generated by the frontend.*
"""


# ── Generic helpers ───────────────────────────────────────────────────────────
def check_sandbox_health() -> bool:
    try:
        r = requests.get(f"{SANDBOX_URL}/health", timeout=3)
        return r.status_code == 200
    except Exception:
        return False


def _error_result(skill_id: str, message: str, *, exec_time: float = 0.0) -> dict:
    return {
        "status": "error",
        "skill_id": skill_id,
        "output": "",
        "error": message,
        "execution_time_seconds": exec_time,
        "source": "live",
    }


# ── Catalog API ───────────────────────────────────────────────────────────────
def list_skills(team: str | None = None, category: str | None = None,
                search: str | None = None) -> list[dict]:
    params = {k: v for k, v in {"team": team, "category": category, "search": search}.items() if v}
    try:
        r = requests.get(f"{SANDBOX_URL}/skills", params=params, timeout=5)
        r.raise_for_status()
        return r.json()
    except Exception:
        return []


def list_all_skills(status: str | None = None) -> list[dict]:
    params = {"status": status} if status else {}
    try:
        r = requests.get(f"{SANDBOX_URL}/skills/all", params=params, timeout=5)
        r.raise_for_status()
        return r.json()
    except Exception:
        return []


def get_skill(skill_id: str) -> dict | None:
    try:
        r = requests.get(f"{SANDBOX_URL}/skills/{skill_id}", timeout=5)
        if r.status_code == 404:
            return None
        r.raise_for_status()
        return r.json()
    except Exception:
        return None


def create_skill(metadata: dict, skill_md: str = "") -> dict:
    try:
        r = requests.post(
            f"{SANDBOX_URL}/skills",
            json={"metadata": metadata, "skill_md": skill_md},
            timeout=10,
        )
        if r.status_code == 409:
            return {"status": "error", "error": "A skill with that ID already exists."}
        r.raise_for_status()
        return {"status": "success", "skill": r.json()}
    except requests.exceptions.HTTPError as e:
        return {"status": "error", "error": _detail(e)}
    except Exception as e:
        return {"status": "error", "error": f"Backend unreachable: {e}"}


def update_skill(skill_id: str, metadata: dict, skill_md: str = "") -> dict:
    try:
        r = requests.put(
            f"{SANDBOX_URL}/skills/{skill_id}",
            json={"metadata": metadata, "skill_md": skill_md},
            timeout=10,
        )
        r.raise_for_status()
        return {"status": "success", "skill": r.json()}
    except requests.exceptions.HTTPError as e:
        return {"status": "error", "error": _detail(e)}
    except Exception as e:
        return {"status": "error", "error": f"Backend unreachable: {e}"}


def approve_skill(skill_id: str) -> dict:
    try:
        r = requests.post(f"{SANDBOX_URL}/skills/{skill_id}/approve", timeout=10)
        r.raise_for_status()
        return {"status": "success", "skill": r.json()}
    except requests.exceptions.HTTPError as e:
        return {"status": "error", "error": _detail(e)}
    except Exception as e:
        return {"status": "error", "error": f"Backend unreachable: {e}"}


def reject_skill(skill_id: str, reason: str = "") -> dict:
    try:
        r = requests.post(
            f"{SANDBOX_URL}/skills/{skill_id}/reject",
            json={"reason": reason},
            timeout=10,
        )
        r.raise_for_status()
        return {"status": "success", "skill": r.json()}
    except requests.exceptions.HTTPError as e:
        return {"status": "error", "error": _detail(e)}
    except Exception as e:
        return {"status": "error", "error": f"Backend unreachable: {e}"}


def admin_update_skill(skill_id: str, metadata: dict, skill_md: str = "") -> dict:
    try:
        r = requests.patch(
            f"{SANDBOX_URL}/skills/{skill_id}",
            json={"metadata": metadata, "skill_md": skill_md},
            timeout=10,
        )
        r.raise_for_status()
        return {"status": "success", "skill": r.json()}
    except requests.exceptions.HTTPError as e:
        return {"status": "error", "error": _detail(e)}
    except Exception as e:
        return {"status": "error", "error": f"Backend unreachable: {e}"}


def delete_skill(skill_id: str) -> dict:
    try:
        r = requests.delete(f"{SANDBOX_URL}/skills/{skill_id}", timeout=10)
        if r.status_code in (200, 204):
            return {"status": "success"}
        r.raise_for_status()
        return {"status": "success"}
    except requests.exceptions.HTTPError as e:
        return {"status": "error", "error": _detail(e)}
    except Exception as e:
        return {"status": "error", "error": f"Backend unreachable: {e}"}


# ── Skill execution ───────────────────────────────────────────────────────────
def run_skill(skill_id: str, inputs: dict, files: dict | None = None) -> dict:
    """
    Run a skill end-to-end.

    files: optional {field_key: UploadedFile or (filename, bytes)} — sent as multipart.
    """
    multipart_files = _build_multipart(files or {})
    try:
        response = requests.post(
            f"{SANDBOX_URL}/run-skill",
            data={"skill_id": skill_id, "inputs": json.dumps(inputs)},
            files=multipart_files,
            timeout=RUN_TIMEOUT_SECONDS,
        )
        response.raise_for_status()
        return response.json()
    except requests.exceptions.ConnectionError:
        # Backend offline — fall back to mock so the UI keeps working for demos
        return _mock_response(skill_id, inputs)
    except requests.exceptions.Timeout:
        return _error_result(
            skill_id,
            f"Skill timed out after {RUN_TIMEOUT_SECONDS}s. "
            "The sandbox may be overloaded or the task is too long.",
            exec_time=RUN_TIMEOUT_SECONDS,
        )
    except requests.exceptions.HTTPError as e:
        return _error_result(skill_id, _detail(e))
    except Exception as e:
        return _error_result(skill_id, f"Unexpected error: {e}")


def stream_skill_run(skill_id: str, inputs: dict, files: dict | None = None):
    """
    Generator that streams stage events from /run-skill/stream.
    Yields dicts: {stage, ...} — same shape as stream_skill on the backend.
    Falls back to a single error event if the backend is unreachable.
    """
    multipart_files = _build_multipart(files or {})
    try:
        r = requests.post(
            f"{SANDBOX_URL}/run-skill/stream",
            data={"skill_id": skill_id, "inputs": json.dumps(inputs)},
            files=multipart_files,
            stream=True,
            timeout=RUN_TIMEOUT_SECONDS,
        )
        r.raise_for_status()
        for raw_line in r.iter_lines():
            if raw_line:
                try:
                    yield json.loads(raw_line)
                except json.JSONDecodeError:
                    pass
    except requests.exceptions.ConnectionError:
        yield {"stage": "error", "failed_at": "connection", "error": "Backend offline — start the backend with uvicorn backend.api:app --port 8000"}
    except requests.exceptions.Timeout:
        yield {"stage": "error", "failed_at": "running", "error": f"Skill timed out after {RUN_TIMEOUT_SECONDS}s"}
    except requests.exceptions.HTTPError as e:
        yield {"stage": "error", "failed_at": "connection", "error": _detail(e)}
    except Exception as e:
        yield {"stage": "error", "failed_at": "connection", "error": str(e)}


# ── Internal helpers ──────────────────────────────────────────────────────────
def _build_multipart(files: dict) -> list[tuple]:
    out: list[tuple] = []
    for _, f in files.items():
        if f is None:
            continue
        if hasattr(f, "read") and hasattr(f, "name"):
            data = f.read()
            out.append(("files", (f.name, data)))
        elif isinstance(f, tuple) and len(f) == 2:
            out.append(("files", (f[0], f[1])))
    return out


def _detail(e: requests.exceptions.HTTPError) -> str:
    try:
        body = e.response.json()
        return body.get("detail") or body.get("error") or str(e)
    except Exception:
        return str(e)


def _mock_response(skill_id: str, inputs: dict) -> dict:
    exec_time = round(random.uniform(8.5, 17.5), 1)
    time.sleep(min(exec_time / 10, 2))

    if skill_id == "srs-creator":
        output = MOCK_SRS
    elif skill_id == "test-case-generator":
        output = MOCK_TEST_CASES
    else:
        bullets = "\n".join(f"- **{k}:** {v}" for k, v in inputs.items())
        output = (
            "# Skill Output (mock)\n\n"
            "*Backend offline — start `uvicorn backend.api:app --port 8000` for real runs.*\n\n"
            f"**Inputs received:**\n{bullets}\n"
        )

    return {
        "status": "success",
        "skill_id": skill_id,
        "output": output,
        "execution_time_seconds": exec_time,
        "source": "mock",
    }
